import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/styles/globals.scss";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";

// const montserrat = Montserrat({
//     subsets: ["latin"],
//     variable: "--font-mont"
// });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${montserrat.className} bg-light w-full min-h-screen`}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
